server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /positions/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            level: level
            request_id: request_id
            user_id: user_id
            route: route
            status: status
            code: code
            message: message
      - labels:
          level:
          route:
          status:
          code:
          user_id:
      - static_labels:
          app: backend
    relabel_configs:
      # Use container label if present for more specific app value
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: app
        action: replace
        regex: '(.+)'
        replacement: '$1'
      - source_labels: ['__meta_docker_container_name']
        target_label: container
        action: replace
        regex: '/(.*)'
        replacement: '$1'
