name: Deploy to Ubuntu via SSH
on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build known_hosts from runner
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -T 10 -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          echo "known_hosts ready"

      - name: Preflight SSH
        run: |
          ssh -vvv -o StrictHostKeyChecking=yes -p "${{ secrets.SSH_PORT }}" \
              "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" 'echo PREOK'

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=yes -p "${{ secrets.SSH_PORT }}" \
              "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
              'bash -lc "/opt/covenant-azor/deploy_remote.sh"'
